from costanti.costanti import *


WINDOW_WIDTH = DISPLAY_WIDTH - 400
WINDOW_HEIGHT = DISPLAY_HEIGHT - 200

EDGE_SIZE = 22
SCREEN_WIDTH = DISPLAY_WIDTH // 2
SCREEN_HEIGHT = DISPLAY_HEIGHT - 130

SCREEN_LEVEL_WIDTH = SCREEN_WIDTH - EDGE_SIZE * 2
SCREEN_LEVEL_HEIGHT = SCREEN_HEIGHT - EDGE_SIZE
SCREEN_LEVEL_X = EDGE_SIZE
SCREEN_LEVEL_Y = EDGE_SIZE

BACKGROUND_WIDTH = SCREEN_LEVEL_WIDTH
BACKGROUND_HEIGHT = SCREEN_LEVEL_HEIGHT

EDGE_TOP_SIZE = (SCREEN_WIDTH, EDGE_SIZE)
EDGE_VERTICAL_SIZE = (EDGE_SIZE, SCREEN_HEIGHT)
EDGE_TOP = (0, 0)
EDGE_LEFT = (0, 0)
EDGE_RIGHT = (SCREEN_LEVEL_WIDTH + EDGE_SIZE, 0)

BUTTON_WIDTH = 250
BUTTON_HEIGHT = 60

BUTTON_COLOR_SIZE = 50

AREA_PADDLE = 350

BRICK_WIDTH = SCREEN_LEVEL_WIDTH / MAX_CLN
BRICK_HEIGHT = (SCREEN_LEVEL_HEIGHT - AREA_PADDLE) / MAX_ROW

BRICK_GRID = dict(
    x=SCREEN_LEVEL_X,
    y=SCREEN_LEVEL_Y,
    width=SCREEN_LEVEL_WIDTH,
    height=SCREEN_LEVEL_HEIGHT - AREA_PADDLE,
    right=EDGE_RIGHT[0],
    bottom=EDGE_SIZE + (SCREEN_LEVEL_HEIGHT - AREA_PADDLE)
)
